### ISSUE TITLE
[iOS] Frame drops / stuttering on fresh install 

### ISSUE THREAD

**Issue by dragoncodes** [rive-app/rive-react-native#183] opened 2023-06-14 06:33 UTC
### Description
We're using the Rive player for a fancy Intro/Welcome animation, but we're seeing that on a fresh install of the app, the animation skips frames and stutters. If the app is restarted, it works fine. 

I can only imagine that the Rive Runtime is caching the values somewhere on the device after the first run (but I could not find this in the codebase)

### Provide a Repro
https://github.com/dragoncodes/rive-intro-repro
The most basic RN project (I created it with Expo for easier setup, but the issue is not related to Expo)

To run the project
```
nvm use 18.14.2
yarn install
yarn ios
```

#### Source `.riv`/`.rev` file
Attached

### Expected behavior
We expect the first run of the app to behave the same as the subsequent runs

https://github.com/rive-app/rive-react-native/assets/7829270/fedd736a-08d6-4742-b6a1-113de91dada7

#### Screenshots

https://github.com/rive-app/rive-react-native/assets/7829270/30830cc6-1c43-4d9d-b4ff-8747ed2e06a6

- Tested on iOS [14, 16]
### Device & Versions (please complete the following information)
- Device: iPhone Device and Simulator 14 Pro, 12 Pro, 12 Max, SE (3rd gen)
- OS: iOS 14, 15, 16
- NPM Version: Tested with `9.5.0` and `7.15.1` 
- Rive RN Version: Tested with `4.0.1` and `4.1.0` (latest)

#### Additional context
We found that if we let the animation run behind the splash screen and then reset the state machine, the problem is not reproduced, but this means that the user waits an additional 2 seconds for the whole animation to finish

[files.zip](https://github.com/rive-app/rive-react-native/files/11742383/files.zip)

**Comment by HayesGordon** [comment] 2023-06-14 07:54
Hi @dragoncodes thanks for the detailed report and provided sample.

We'll investigate and get back to you.

**Comment by HayesGordon** [comment] 2023-06-15 09:08
Hi @dragoncodes , I'm able to reproduce your issue. It's not an issue with ReactNative, nor an issue with the Rive iOS runtime. The problem is with Skia, the underlying renderer we use on iOS.

I was able to confirm that the same animation will stutter on our Flutter runtime when the target renderer is Skia on iOS, but the problem is resolved when using Flutter's new renderer Impeller.

To give you some background context, the first time that an animation runs on Skia it might perform a lot of shader compilation that it then caches on disk to reuse for later runs. That is why you see the extreme stuttering the first time (as these shaders are being compiled) and then subsequent runs are smooth. Flutter has written on the topic here if you're interested: https://docs.flutter.dev/perf/shader

Similar to Flutter's finding we're also transitioning away from Skia with our own custom renderer, that you can read about here: https://rive.app/renderer

I don't have a timeline for when we will replace Skia entirely with our Renderer, unfortunately. But when that happens you'll see significant improvements.

Unfortunately non of the above solves your immediate problem. I gave the above for context, but I think your issue can be resolved by optimising your animation.

At this time I'm not able to do a thorough investigation, as I'm having difficulties importing the files you shared in our editor (which indicates a problem with the file 😄 ). One of our engineers was able to do it in a testing environment and they confirmed that there aren't any large images being used.

That indicates that the majority of the .riv file size is animation related data (path points, animations, key frames, etc). 5mb is quite a lot, as this animation isn't that complex visually.

Did you design the whole animation in Rive, or was this imported from a Lottie animation? It could be that something went wrong with that process, and very often those types of imports adds a lot of additional keys and animations that aren't necessary.

- Short term, I'd ask you to investigate if you can reduce the amount of keyframes you're using. If there are any complex paths you're using it may even be better to flatten them to an image, and then animating the image.

- You can also check to make sure that snap keys are not set to an unreasonably high number (not larger than 60)

![CleanShot 2023-06-15 at 11 03 30](https://github.com/rive-app/rive-react-native/assets/13705472/b90e0433-9f9a-43d0-b684-e3f7fd0cede6)

- Make sure there aren't any unused animation timelines, artboards, etc.

- You can optimise your animations by keying bones, instead of individual path points (which will also reduce file size).

- Confirm that you're not using really large images for your animations

**Comment by HayesGordon** [comment] 2023-06-15 10:02
I was able to review your animation in the editor.

And I see now that the animation is much more complex than the initial start screen!

After a very quick look I think the majority of the initial startup complexity is as a result of the `Fractional Shares Planet` group, and then as the **transition** input changes you zoom into that group and expand more and more component.

It will be better if you can setup the animation in such a way that it does not perform any unnecessary calculations. Instead of animating the whole `Fractional Shared Planet` group at the start, you could instead use an image, or a less complex object.

Then once you start zooming in only then swap it out for a more complex version with all the components. The most efficient way to toggle certain components on/off (or swapping between values) is by using [Solos](https://help.rive.app/editor/manipulating-shapes/solos).

Another way of thinking about this is a DOP (Depth of Field). Where you only add more detail as you zoom in closer, instead of drawing all these positions/images at the start and animating them when not needed.

**Comment by dragoncodes** [comment] 2023-06-15 10:39
Thank you for your prompt and thorough response! You guys are awesome! Keep up the good work!

Your advice in regard to the file is actionable, and we will start experimenting.

The undertaking of switching to your own renderer sounds exciting, and we're eager to try it out!

That being said, I am curious, would it be possible to wait out the Skia initialization before starting the animation?
 
In SDK terms, if I set `autoplay` to `false` and have an `onLoad` method from Rive (one that is called after shader compilation is finished), I can then, theoretically, call `play` without the defects 🤔 

I understand this conflicts with your plans/schedules, but if pointed in the right direction, we're more than willing to submit a PR.

Note: This suggestion is based on the assumption that the shader compilation does not take ~2 seconds.

Again, thank you for your response <3

**Comment by HayesGordon** [comment] 2023-06-15 11:55
We don't handle the caching, instead Skia does. Using Flutter as an example again, they provide tooling to allow you to pre-compile the shaders and package in the SkSL shaders with the app. I don't believe it's possible to wait for Skia to compile the shaders. The shaders are compiled on the fly as you run the animations - and there may be a variety of factors at play here.

I'd need to speak to our team whether something like this is feasible/possible for us. I have limited experience in this domain, but I expect this won't be easy to do, and it also won't align with our plan to switch out renderers at this stage.

Not a great solution, but you could play the animation (hidden behind a black screen) and then simply replay it. First time you open the app that would mean there will be a longer "startup time".

I think for this particular case, I would still suggest trying to reduce the complexity of the animation. Keeping in mind that older devices may struggle more with complex animations that have a lot of moving parts.

**Closed** 2023-06-16 16:08 UTC
Labels: triage
